import Head from "next/head";
import Navbar from "@/components/Navbar";
import styles from "@/styles/Home.module.scss";
import { TypeAnimation } from "react-type-animation";

export default function Home() {

    return (
    <>
        <Head>
            <title>NeueSide - Home</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
        <main className={styles.main}>
            <div className={styles.welcome}>
                <TypeAnimation
                    sequence={[
                        "Welcome to NeueSide!",
                        3000,
                        "",
                        3000
                    ]}
                    speed={50}
                    style={{ fontSize: "5rem", height: "fit-content", paddingBottom: "0.6rem" }}
                    wrapper="span"
                    repeat={Infinity}
                />
            </div>
            <div className={styles.body_first}>
                Heyoo, nice of you to drop by my site. I am planning for this site to be a place where I can
                showcase my projects. You are welcome to have a look around.
            </div>
        </main>
    </>
    )
}