import Navbar from "@/components/Navbar";
import { NeueTextField } from "@/components/NeueTextField";
import Head from "next/head";
import styles from "@/styles/Login.module.scss";

export default function Login() {

    return <>
        <Head>
            <title>NeueSide - Login</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
        <div>
        <main className={styles.main}>
            <h1>Login Form</h1> 
            <div className={styles.login_fields}>
                <div className={styles.text_field_wrapper}>
                    <NeueTextField
                        label="Email"
                    />
                </div>
                <div className={styles.text_field_wrapper}>
                    <NeueTextField
                        label="Password"
                    />
                </div>
            </div>
        </main>
        </div>
    </>
}